Repository openzipkin/zipkin, pull requests merged in 2018-11, with the labels that each got.

#2232 Brings back relative width in trace query screen
  zipkin-ui/js/component_data/default.js
  zipkin-ui/js/component_ui/traceSummary.js
  zipkin-ui/js/component_ui/traceToMustache.js
  zipkin-ui/test/component_data/default.test.js
  zipkin-ui/test/component_ui/traceSummary.test.js
Labels: bug, ui

#2235 Fixes bug in service percentage calculation
  zipkin-ui/js/component_ui/traceSummary.js
  zipkin-ui/test/component_ui/traceSummary.test.js
Labels: bug, ui

#2267 Moves UI tests to v2 data, fixes a couple glitches
  zipkin-ui/js/component_ui/traceSummary.js
  zipkin-ui/js/component_ui/traceToMustache.js
  zipkin-ui/js/skew.js
  zipkin-ui/test/component_data/default.test.js
  zipkin-ui/test/component_ui/spanPanel.test.js
  zipkin-ui/test/component_ui/traceSummary.test.js
  zipkin-ui/test/component_ui/traceTestHelpers.js
  zipkin-ui/test/component_ui/traceToMustache.test.js
Labels: bug, ui

#2264 Fixes Expand All and Collapse All
  zipkin-ui/css/main.scss
  zipkin-ui/css/summary.css
  zipkin-ui/css/traces.css
  zipkin-ui/js/component_ui/filterLabel.js
  zipkin-ui/js/component_ui/trace.js
  zipkin-ui/js/component_ui/traceFilters.js
  zipkin-ui/js/component_ui/traces.js
  zipkin-ui/js/page/trace.js
  zipkin-ui/js/page/traceViewer.js
  zipkin-ui/templates/trace.mustache
  zipkin-ui/templates/traceViewer.mustache
  zipkin-ui/test/component_ui/trace.test.js
  zipkin-ui/test/component_ui/traceTestHelpers.js
Labels: bug, ui

#2272 Corrects counts in trace detail screen
  zipkin-ui/js/component_data/default.js
  zipkin-ui/js/component_data/trace.js
  zipkin-ui/js/component_ui/traceToMustache.js
  zipkin-ui/js/component_ui/uploadTrace.js
  zipkin-ui/js/skew.js
  zipkin-ui/js/spanNode.js
  zipkin-ui/test/component_data/trace.test.js
  zipkin-ui/test/component_ui/trace.test.js
  zipkin-ui/test/component_ui/traceToMustache.test.js
  zipkin-ui/test/skew.test.js
  zipkin-ui/test/spanNode.test.js
Labels: bug, ui

#2277 Removes a UI transformation step processing span timeline
  zipkin-ui/css/trace.css
  zipkin-ui/js/component_ui/traceConstants.js
  zipkin-ui/js/component_ui/traceToMustache.js
  zipkin-ui/js/page/trace.js
  zipkin-ui/js/spanConverter.js
  zipkin-ui/js/spanNode.js
  zipkin-ui/templates/trace.mustache
  zipkin-ui/templates/traceViewer.mustache
  zipkin-ui/test/component_data/trace.test.js
  zipkin-ui/test/component_ui/traceToMustache.test.js
  zipkin-ui/test/spanConverter.test.js
  zipkin-ui/testdata/netflix.json
Labels: enhancement, ui

#2278 Renames UI references of binary annotation to tag
  zipkin-ui/css/trace.css
  zipkin-ui/js/component_ui/spanPanel.js
  zipkin-ui/js/component_ui/trace.js
  zipkin-ui/js/component_ui/traceToMustache.js
  zipkin-ui/js/spanConverter.js
  zipkin-ui/static/traces.properties
  zipkin-ui/static/traces_it_IT.properties
  zipkin-ui/static/traces_zh_CN.properties
  zipkin-ui/static/traces_zh_TW.properties
  zipkin-ui/templates/index.mustache
  zipkin-ui/templates/trace.mustache
  zipkin-ui/templates/traceViewer.mustache
  zipkin-ui/test/component_data/trace.test.js
  zipkin-ui/test/component_ui/spanPanel.test.js
  zipkin-ui/test/component_ui/traceToMustache.test.js
  zipkin-ui/test/spanConverter.test.js
Labels: enhancement, ui

#2280 Deduplicates annotation processing logic
  zipkin-ui/js/component_data/trace.js
  zipkin-ui/js/component_ui/traceToMustache.js
  zipkin-ui/js/component_ui/uploadTrace.js
  zipkin-ui/js/spanConverter.js
  zipkin-ui/test/component_ui/trace.test.js
  zipkin-ui/test/component_ui/traceToMustache.test.js
  zipkin-ui/test/spanConverter.test.js
Labels: ui

#2279 Makes UI merge logic lenient to missing shared flag on server side
  zipkin-ui/js/spanCleaner.js
  zipkin-ui/js/spanNode.js
  zipkin-ui/test/skew.test.js
  zipkin-ui/test/spanCleaner.test.js
  zipkin-ui/testdata/netflix.json
Labels: bug, ui

#2282 Fix bugs in UI skew logic relating to headless traces
  zipkin-ui/js/skew.js
  zipkin-ui/test/component_ui/trace.test.js
  zipkin-ui/test/component_ui/traceTestHelpers.js
  zipkin-ui/test/component_ui/traceToMustache.test.js
  zipkin-ui/test/skew.test.js
  zipkin-ui/testdata/skew.json
Labels: bug, ui

#2292 Fixes suffix μ -> μs
  zipkin-ui/js/component_ui/traceSummary.js
  zipkin-ui/test/component_data/default.test.js
  zipkin-ui/test/component_data/trace.test.js
  zipkin-ui/test/component_ui/traceSummary.test.js
Labels: bug, ui

#2288 Aligns json button right and deletes dead json button style
  zipkin-ui/css/main.scss
  zipkin-ui/templates/trace.mustache
Labels: bug, ui

#2294 Tightens UI logic so we don't have to consider empty span nodes
  zipkin-ui/js/component_data/default.js
  zipkin-ui/js/spanCleaner.js
  zipkin-ui/js/spanNode.js
  zipkin-ui/test/component_data/default.test.js
  zipkin-ui/test/component_data/trace.test.js
  zipkin-ui/test/spanNode.test.js
Labels: ui

#2299 Rewrote duration to be more efficient because it was there
  zipkin-ui/js/component_ui/traceSummary.js
Labels: ui

#2300 Removes data dependency between index screen and trace detail
  zipkin-ui/js/component_ui/traceSummary.js
  zipkin-ui/js/component_ui/traceToMustache.js
  zipkin-ui/test/component_ui/traceSummary.test.js
  zipkin-ui/test/component_ui/traceToMustache.test.js
Labels: techdebt, ui

#2301 Uses SpanNode to generate the trace tree for the detail screen
  zipkin-ui/js/component_ui/traceToMustache.js
  zipkin-ui/js/spanNode.js
  zipkin-ui/test/component_data/trace.test.js
  zipkin-ui/test/component_ui/traceToMustache.test.js
  zipkin-ui/test/spanNode.test.js
Labels: enhancement, ui
