Repository openzipkin/zipkin, pull requests merged in 2019-02, with the labels that each got.

#2373 Add title
  zipkin-lens/src/components/App/index.js
Labels: chore, ui

#2375 Add links of GitHub/Twitter/Gitter to sidebar
  zipkin-lens/scss/components/_sidebar.scss
  zipkin-lens/src/components/App/Sidebar.js
Labels: enhancement, ui

#2374 Do npm audit fix in lens
  zipkin-lens/package-lock.json
  zipkin-lens/package.json
Labels: chore, ui

#2379 Do not try to create RabbitMQ queue if one already exists
  zipkin-collector/rabbitmq/src/main/java/zipkin2/collector/rabbitmq/RabbitMQCollector.java
  zipkin-collector/rabbitmq/src/test/java/zipkin2/collector/rabbitmq/ITRabbitMQCollector.java
Labels: bug, rabbitmq

#2382 Use react-numeric-input for limit condition
  zipkin-lens/package-lock.json
  zipkin-lens/package.json
  zipkin-lens/scss/components/_condition-limit.scss
  zipkin-lens/scss/custom/_rc-input-number.scss
  zipkin-lens/scss/main.scss
  zipkin-lens/src/components/GlobalSearch/ConditionLimit.js
  zipkin-lens/src/components/GlobalSearch/index.js
  zipkin-lens/src/reducers/global-search.js
Labels: bug, enhancement, ui

#2381 Rename annotationQuery to tags
  zipkin-lens/scss/components/_condition-tags.scss
  zipkin-lens/scss/main.scss
  zipkin-lens/src/components/GlobalSearch/ConditionTags.js
  zipkin-lens/src/components/GlobalSearch/index.js
  zipkin-lens/src/reducers/global-search.test.js
  zipkin-lens/src/util/global-search.js
  zipkin-lens/src/util/global-search.test.js
Labels: chore, ui

#2386 Show both client and server timings
  zipkin-lens/scss/components/_timeline.scss
  zipkin-lens/src/components/Timeline/Span.js
  zipkin-lens/src/components/Timeline/index.js
Labels: enhancement, ui

#2393 Fix a css bug of search bar in Lens
  zipkin-lens/scss/components/_global-search.scss
Labels: bug, ui

#2397 Shows different tag values when client and server differ
  zipkin-lens/src/zipkin/span-row.js
  zipkin-lens/src/zipkin/span-row.test.js
  zipkin-ui/js/component_ui/spanRow.js
  zipkin-ui/templates/trace.mustache
  zipkin-ui/templates/traceViewer.mustache
  zipkin-ui/test/component_data/trace.test.js
  zipkin-ui/test/component_ui/spanRow.test.js
Labels: bug, ui

#2400 Updates versions, notable Spring Boot 2.1.3
  pom.xml
  zipkin-lens/pom.xml
  zipkin-server/pom.xml
  zipkin-ui/pom.xml
  zipkin/src/test/java/zipkin2/internal/SpanNodeTest.java
Labels: chore

#2404 Suggests use of Zipkin Lens when running a standard server
  zipkin-autoconfigure/ui/src/main/java/zipkin2/autoconfigure/ui/ZipkinUiAutoConfiguration.java
  zipkin-autoconfigure/ui/src/main/java/zipkin2/autoconfigure/ui/ZipkinUiProperties.java
  zipkin-autoconfigure/ui/src/test/java/zipkin2/autoconfigure/ui/ZipkinUiAutoConfigurationTest.java
  zipkin-server/README.md
  zipkin-server/src/main/resources/zipkin-server-shared.yml
  zipkin-ui/js/component_ui/goToLens.js
  zipkin-ui/js/config.js
  zipkin-ui/js/page/common.js
  zipkin-ui/package.json
  zipkin-ui/templates/index.mustache
  zipkin-ui/templates/layout.mustache
Labels: enhancement, ui

#2407 Fix css bugs of limit condition and lookback condition components in zipkin lens
  zipkin-lens/package-lock.json
  zipkin-lens/scss/components/_condition-lookback.scss
  zipkin-lens/scss/components/_global-search.scss
  zipkin-lens/scss/custom/_rc-time-picker.scss
  zipkin-lens/src/components/GlobalSearch/ConditionLimit.js
Labels: bug, ui

#2409 Refactor prop-types
  zipkin-lens/src/components/Browser/TraceSummary.js
  zipkin-lens/src/components/Browser/index.js
  zipkin-lens/src/components/GlobalSearch/ConditionLimit.js
  zipkin-lens/src/components/GlobalSearch/index.js
  zipkin-lens/src/components/Timeline/Span.js
  zipkin-lens/src/components/Timeline/SpanInfo.js
  zipkin-lens/src/components/Timeline/index.js
  zipkin-lens/src/prop-types/index.js
  zipkin-lens/src/reducers/global-search.js
Labels: enhancement, ui

#2415 Works around encoding bug in zipkin-ruby by leniently parsing
  zipkin-storage/mysql-v1/src/test/java/zipkin2/storage/mysql/v1/LazyMySQLStorage.java
  zipkin/src/main/java/zipkin2/v1/V1SpanConverter.java
  zipkin/src/test/java/zipkin2/v1/V1SpanConverterTest.java
Labels: techdebt
