Repository openzipkin/zipkin, pull requests merged in 2019-07, with the labels that each got.

#2657 Fix bugs that fetching traces with old conditions
  zipkin-lens/src/components/DiscoverPage/DiscoverPage.jsx
  zipkin-lens/src/components/GlobalSearch/GlobalSearch.jsx
Labels: bug, ui

#2658 Fix an bug that can not scroll on the Trace page
  zipkin-lens/src/components/App/Layout.jsx
Labels: bug, ui

#2659 Update babel version
  zipkin-lens/.babelrc
  zipkin-lens/babel.config.js
  zipkin-lens/package-lock.json
  zipkin-lens/package.json
  zipkin-lens/src/index.js
Labels: techdebt, ui

#2664 Change endTs when enter key or search button is clicked
  zipkin-lens/src/components/DiscoverPage/DiscoverPage.jsx
  zipkin-lens/src/components/DiscoverPage/api.js
  zipkin-lens/src/components/DiscoverPage/api.test.js
  zipkin-lens/src/components/GlobalSearch/conditions/LookbackCondition.jsx
  zipkin-lens/src/reducers/global-search.js
Labels: bug, ui

#2687 Cleans up some Elasticsearch configuration prior to release
  zipkin-server/README.md
  zipkin-server/src/main/java/zipkin2/server/internal/elasticsearch/ZipkinElasticsearchStorageAutoConfiguration.java
  zipkin-server/src/main/java/zipkin2/server/internal/elasticsearch/ZipkinElasticsearchStorageProperties.java
  zipkin-server/src/main/resources/zipkin-server-shared.yml
  zipkin-server/src/test/java/zipkin2/elasticsearch/ZipkinElasticsearchStorageAutoConfigurationTest.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/ElasticsearchStorage.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/internal/client/HttpCall.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/ElasticsearchSpanConsumerTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/internal/client/HttpCallTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/internal/client/SearchCallFactoryTest.java
Labels: elasticsearch, techdebt

#2693 Performs cleanups in Elasticsearch code, seeking better test coverage
  pom.xml
  zipkin-storage/cassandra-v1/src/test/java/zipkin2/storage/cassandra/v1/ITCassandraStorage.java
  zipkin-storage/cassandra/src/test/java/zipkin2/storage/cassandra/ITCassandraStorage.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/BodyConverters.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/ElasticsearchStorage.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/EnsureIndexTemplate.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/VersionSpecificTemplates.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/internal/BasicAuthInterceptor.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/internal/BulkCallBuilder.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/internal/JsonReaders.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/internal/JsonSerializers.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/internal/client/HttpCall.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/internal/client/RawContentLoggingClient.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/internal/client/SearchResultConverter.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/ElasticsearchSpanConsumerTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/ElasticsearchSpanStoreTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/ElasticsearchStorageTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/HttpCallTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/JsonReadersTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/JsonSerializersTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/SearchResultConverterTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/TestResponses.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/VersionSpecificTemplatesTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/integration/ITElasticsearchStorageV6.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/integration/ITElasticsearchStorageV7.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/internal/BasicAuthInterceptorTest.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/internal/BulkCallBuilderTest.java
  zipkin-storage/mysql-v1/src/test/java/zipkin2/storage/mysql/v1/ITMySQLStorage.java
Labels: elasticsearch, techdebt

#2677 Improve performance of trace page
  zipkin-lens/src/actions/trace-action.js
  zipkin-lens/src/actions/trace-action.test.js
  zipkin-lens/src/actions/traces-action.js
  zipkin-lens/src/actions/traces-action.test.js
  zipkin-lens/src/components/Browser/Browser.jsx
  zipkin-lens/src/components/DiscoverPage/DiscoverPage.jsx
  zipkin-lens/src/components/TracePage/index.jsx
  zipkin-lens/src/constants/action-types.js
  zipkin-lens/src/containers/Browser/BrowserContainer.js
  zipkin-lens/src/containers/TracePage/TracePageContainer.js
  zipkin-lens/src/reducers/trace.js
  zipkin-lens/src/reducers/trace.test.js
  zipkin-lens/src/reducers/traces.js
  zipkin-lens/src/reducers/traces.test.js
Labels: enhancement, performance, ui

#2691 Add rootServiceAndSpanName function
  zipkin-lens/src/zipkin/index.js
  zipkin-lens/src/zipkin/span-row.js
  zipkin-lens/src/zipkin/trace.js
  zipkin-lens/src/zipkin/trace.test.js
Labels: enhancement, help wanted, ui

#2702 Fix LookbackCondition's warning
  zipkin-lens/src/components/GlobalSearch/conditions/LookbackCondition.jsx
Labels: bug, ui

#2690 Redesign service badge in Lens
  zipkin-lens/scss/components/_search-condition.scss
  zipkin-lens/scss/components/_service-name-badge.scss
  zipkin-lens/scss/main.scss
  zipkin-lens/src/colors/index.js
  zipkin-lens/src/components/Browser/TraceSummary/TraceSummary.jsx
  zipkin-lens/src/components/Common/ServiceBadge.jsx
  zipkin-lens/src/components/Common/ServiceBadge.test.js
  zipkin-lens/src/components/Common/ServiceNameBadge.jsx
  zipkin-lens/src/components/Dependencies/DependenciesSidebar.jsx
  zipkin-lens/src/components/MiniTimeline/MiniTimelineGraph.jsx
  zipkin-lens/src/components/Timeline/TimelineSpan.jsx
  zipkin-lens/src/components/Timeline/TimelineSpanData.jsx
  zipkin-lens/src/util/color.js
Labels: enhancement, ui

#2704 Avoid fetching traces when the search criteria is not changed
  zipkin-lens/src/actions/global-search-action.js
  zipkin-lens/src/actions/traces-action.js
  zipkin-lens/src/actions/traces-action.test.js
  zipkin-lens/src/components/Browser/Browser.jsx
  zipkin-lens/src/components/Browser/Browser.test.js
  zipkin-lens/src/components/DiscoverPage/DiscoverPage.jsx
  zipkin-lens/src/components/DiscoverPage/api.js
  zipkin-lens/src/components/DiscoverPage/api.test.js
  zipkin-lens/src/constants/action-types.js
  zipkin-lens/src/containers/Browser/BrowserContainer.js
  zipkin-lens/src/reducers/global-search.js
  zipkin-lens/src/reducers/traces.js
  zipkin-lens/src/reducers/traces.test.js
Labels: enhancement, ui

#2656 Redesign trace search page
  zipkin-lens/scss/components/_browser-header.scss
  zipkin-lens/scss/components/_browser-results.scss
  zipkin-lens/scss/components/_browser.scss
  zipkin-lens/scss/components/_trace-page.scss
  zipkin-lens/scss/components/_trace-summary-bar.scss
  zipkin-lens/scss/components/_trace-summary-buttons.scss
  zipkin-lens/scss/components/_trace-summary-upper-bar.scss
  zipkin-lens/scss/components/_trace-summary.scss
  zipkin-lens/scss/main.scss
  zipkin-lens/src/components/Browser/Browser.jsx
  zipkin-lens/src/components/Browser/Browser.test.js
  zipkin-lens/src/components/Browser/BrowserHeader.jsx
  zipkin-lens/src/components/Browser/BrowserHeader.test.js
  zipkin-lens/src/components/Browser/BrowserResults.jsx
  zipkin-lens/src/components/Browser/BrowserResults.test.js
  zipkin-lens/src/components/Browser/TraceSummary/TraceSummary.jsx
  zipkin-lens/src/components/Browser/TraceSummary/TraceSummary.test.js
  zipkin-lens/src/components/Browser/TraceSummary/TraceSummaryBar.jsx
  zipkin-lens/src/components/Browser/TraceSummary/TraceSummaryBar.test.js
  zipkin-lens/src/components/Browser/TraceSummary/TraceSummaryButtons.jsx
  zipkin-lens/src/components/Browser/TraceSummary/TraceSummaryUpperBar.jsx
  zipkin-lens/src/components/Browser/TraceSummary/TraceSummaryUpperBar.test.js
  zipkin-lens/src/components/Browser/sorting.test.js
  zipkin-lens/src/components/DiscoverPage/DependenciesTab/DependenciesTab.jsx
  zipkin-lens/src/components/DiscoverPage/DependenciesTab/index.js
  zipkin-lens/src/components/DiscoverPage/DiscoverPage.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/ServiceFilter.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/ServiceFilter.test.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/ServiceFilterPopover.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/ServiceFilterPopover.test.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTab.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTab.test.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTable.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableHead.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableHead.test.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableRow.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableRow.test.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/index.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/util.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/util.test.js
  zipkin-lens/src/containers/Browser/BrowserContainer.js
Labels: enhancement, ui
