Repository openzipkin/zipkin, pull requests merged in 2019-01, with the labels that each got.

#2345 use the client remote service name instead of the client local service name
  zipkin-ui/js/component_ui/spanRow.js
  zipkin-ui/js/component_ui/traceToMustache.js
  zipkin-ui/test/component_ui/spanRow.test.js
Labels: ui

#2358 Add favicon for zipkin-lens
  zipkin-lens/static/favicon.ico
  zipkin-lens/webpack.dev.config.js
  zipkin-lens/webpack.prod.config.js
Labels: chore, ui

#2357 Add autocompleteTags feature to zipkin-lens
  zipkin-lens/src/actions/autocomplete-keys-action.js
  zipkin-lens/src/actions/autocomplete-keys-action.test.js
  zipkin-lens/src/actions/autocomplete-values-action.js
  zipkin-lens/src/actions/autocomplete-values-action.test.js
  zipkin-lens/src/components/GlobalSearch/ConditionName.js
  zipkin-lens/src/components/GlobalSearch/SearchCondition.js
  zipkin-lens/src/components/GlobalSearch/index.js
  zipkin-lens/src/constants/action-types.js
  zipkin-lens/src/constants/api.js
  zipkin-lens/src/containers/GlobalSearch/GlobalSearchContainer.js
  zipkin-lens/src/reducers/autocomplete-keys.js
  zipkin-lens/src/reducers/autocomplete-keys.test.js
  zipkin-lens/src/reducers/autocomplete-values.js
  zipkin-lens/src/reducers/autocomplete-values.test.js
  zipkin-lens/src/reducers/global-search.js
  zipkin-lens/src/reducers/global-search.test.js
  zipkin-lens/src/reducers/index.js
  zipkin-lens/src/util/global-search.js
  zipkin-lens/src/util/global-search.test.js
Labels: enhancement, ui

#2362 Change timeline theme of zipkin-lens
  zipkin-lens/scss/components/_badge.scss
  zipkin-lens/scss/components/_button.scss
  zipkin-lens/scss/components/_header.scss
  zipkin-lens/scss/components/_input.scss
  zipkin-lens/scss/components/_textarea.scss
  zipkin-lens/scss/components/_timeline.scss
  zipkin-lens/scss/main.scss
  zipkin-lens/src/components/Common/Badge.js
  zipkin-lens/src/components/Common/Button.js
  zipkin-lens/src/components/Common/Input.js
  zipkin-lens/src/components/Common/TextArea.js
  zipkin-lens/src/components/Common/TypeAhead.js
  zipkin-lens/src/components/Timeline/Span.js
  zipkin-lens/src/components/Timeline/SpanInfo.js
  zipkin-lens/src/containers/Browser/BrowserContainer.js
Labels: ui

#2363 Adds searching trace when enter key is pressed
  zipkin-lens/package-lock.json
  zipkin-lens/src/components/GlobalSearch/index.js
Labels: enhancement, ui

#2372 Fix autocompleteTags bugs for Elasticsearch
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/ElasticsearchAutocompleteTags.java
  zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/VersionSpecificTemplates.java
Labels: bug, elasticsearch
