Repository openzipkin/zipkin, pull requests merged in 2019-03, with the labels that each got.

#2413 Refactor Timeline component
  zipkin-lens/scss/components/_timeline-header.scss
  zipkin-lens/scss/components/_timeline-span-data.scss
  zipkin-lens/scss/components/_timeline-span.scss
  zipkin-lens/scss/components/_timeline.scss
  zipkin-lens/scss/main.scss
  zipkin-lens/src/components/Timeline/HeaderRow.js
  zipkin-lens/src/components/Timeline/TimelineHeader.js
  zipkin-lens/src/components/Timeline/TimelineSpan.js
  zipkin-lens/src/components/Timeline/TimelineSpanData.js
  zipkin-lens/src/components/Timeline/index.js
  zipkin-lens/src/prop-types/index.js
Labels: enhancement, ui

#2431 Adds integration test for messaging linking and fixes MySQL impl
  zipkin-storage/cassandra-v1/src/test/java/zipkin2/storage/cassandra/v1/ITCassandraStorage.java
  zipkin-storage/cassandra/src/test/java/zipkin2/storage/cassandra/ITCassandraStorage.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/integration/ITElasticsearchStorageV2.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/integration/ITElasticsearchStorageV5.java
  zipkin-storage/elasticsearch/src/test/java/zipkin2/elasticsearch/integration/ITElasticsearchStorageV6.java
  zipkin-storage/mysql-v1/src/main/java/zipkin2/storage/mysql/v1/AggregateDependencies.java
  zipkin-storage/mysql-v1/src/main/java/zipkin2/storage/mysql/v1/DependencyLinkV2SpanIterator.java
  zipkin-storage/mysql-v1/src/test/java/zipkin2/storage/mysql/v1/ITMySQLStorage.java
  zipkin/src/test/java/zipkin2/storage/ITDependencies.java
Labels: bug, mysql

#2433 Tolerates thrift encoding bug we made a long time ago
  zipkin/src/main/java/zipkin2/SpanBytesDecoderDetector.java
  zipkin/src/test/java/zipkin2/SpanBytesDecoderDetectorTest.java
Labels: techdebt

#2446 Fix components that resize timeline columns
  zipkin-lens/src/components/Timeline/TimelineHeader.js
  zipkin-lens/src/components/Timeline/index.js
Labels: bug, ui

#2447 Support upload trace in Zipkin Lens UI
  zipkin-lens/package-lock.json
  zipkin-lens/package.json
  zipkin-lens/scss/components/_condition-trace-id.scss
  zipkin-lens/scss/components/_global-dropdown-menu.scss
  zipkin-lens/scss/components/_global-search.scss
  zipkin-lens/scss/components/_mini-timeline.scss
  zipkin-lens/scss/components/_trace-page.scss
  zipkin-lens/scss/components/_trace-viewer.scss
  zipkin-lens/scss/custom/_react-modal.scss
  zipkin-lens/scss/main.scss
  zipkin-lens/src/actions/trace-viewer-action.js
  zipkin-lens/src/actions/trace-viewer.test.js
  zipkin-lens/src/components/App/index.js
  zipkin-lens/src/components/DetailedTraceSummary/index.js
  zipkin-lens/src/components/GlobalSearch/ConditionTraceId.js
  zipkin-lens/src/components/GlobalSearch/GlobalDropdownMenu.js
  zipkin-lens/src/components/GlobalSearch/index.js
  zipkin-lens/src/components/MiniTimeline/index.js
  zipkin-lens/src/components/TracePage/index.js
  zipkin-lens/src/components/TraceViewer/index.js
  zipkin-lens/src/constants/action-types.js
  zipkin-lens/src/containers/GlobalSearch/GlobalDropdownMenuContainer.js
  zipkin-lens/src/containers/TracePage/TracePageContainer.js
  zipkin-lens/src/containers/TraceViewer/TraceViewerContainer.js
  zipkin-lens/src/index.js
  zipkin-lens/src/reducers/index.js
  zipkin-lens/src/reducers/trace-viewer.js
  zipkin-lens/src/util/global-search.js
  zipkin-lens/src/util/global-search.test.js
  zipkin-lens/src/util/trace.js
  zipkin-lens/src/util/trace.test.js
Labels: enhancement, ui
