Repository openzipkin/zipkin, pull requests merged in 2020-09, with the labels that each got.

#3180 Improve search result table's design
  zipkin-lens/package.json
  zipkin-lens/src/components/DiscoverPage/DiscoverPageContent.tsx
  zipkin-lens/src/components/DiscoverPage/TraceSummaryRow.tsx
  zipkin-lens/src/components/DiscoverPage/TraceSummaryTable.tsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/ServiceFilter.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/ServiceFilter.test.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/ServiceFilterPopover.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/ServiceFilterPopover.test.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTab.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTab.test.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTable.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableHead.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableHead.test.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableRow.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableRow.test.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/util.js
  zipkin-lens/src/components/DiscoverPage/TracesTab/util.test.js
  zipkin-lens/src/components/common/ServiceBadge.jsx
  zipkin-lens/src/models/TraceSummary.ts
  zipkin-lens/src/translations/en/messages.js
  zipkin-lens/src/translations/en/messages.json
  zipkin-lens/src/translations/es/messages.js
  zipkin-lens/src/translations/es/messages.json
  zipkin-lens/src/translations/zh-cn/messages.js
  zipkin-lens/src/translations/zh-cn/messages.json
  zipkin-lens/src/zipkin/trace.js
Labels: enhancement, ui

#3198 TypeScriptize Layout component
  zipkin-lens/src/components/App/Layout.tsx
  zipkin-lens/src/react-app-env.d.ts
Labels: techdebt, ui

#3199 Remove unnecessary css
  zipkin-lens/src/css/base.css
  zipkin-lens/src/index.css
  zipkin-lens/src/index.tsx
Labels: ui

#3200 Remove unused files
  zipkin-lens/src/util/api.js
  zipkin-lens/src/util/color.js
  zipkin-lens/test.json
Labels: ui

#3202 Simplify the open/close logic of the Lookback menu
  zipkin-lens/src/components/DiscoverPage/DiscoverPageContent.tsx
  zipkin-lens/src/components/DiscoverPage/LookbackMenu.tsx
Labels: ui

#3204 Removes orphaned maxSpanDurationStr no longer used in the UI
  zipkin-lens/src/zipkin/trace.js
  zipkin-lens/src/zipkin/trace.test.js
Labels: techdebt, ui

#3205 Removes dead code from Lens
  zipkin-lens/src/components/DependenciesPage/DependenciesGraph.tsx
  zipkin-lens/src/components/DiscoverPage/lookback.ts
  zipkin-lens/src/slices/remoteServicesSlice.ts
  zipkin-lens/src/slices/spansSlice.ts
  zipkin-lens/src/store/index.ts
  zipkin-lens/src/zipkin/trace-constants.js
  zipkin-lens/src/zipkin/trace.js
  zipkin-lens/src/zipkin/trace.test.js
Labels: techdebt, ui

#3203 Improve Redux traces data-flow code
  zipkin-lens/package-lock.json
  zipkin-lens/package.json
  zipkin-lens/src/actions/trace-action.js
  zipkin-lens/src/actions/trace-action.test.js
  zipkin-lens/src/actions/trace-viewer.test.js
  zipkin-lens/src/actions/traces-action.js
  zipkin-lens/src/actions/traces-action.test.js
  zipkin-lens/src/components/App/Layout.tsx
  zipkin-lens/src/components/DependenciesPage/DependenciesPage.tsx
  zipkin-lens/src/components/DiscoverPage/DiscoverPageContent.tsx
  zipkin-lens/src/components/TracePage/MessageBar.jsx
  zipkin-lens/src/components/TracePage/TracePage.jsx
  zipkin-lens/src/components/TracePage/TracePage.test.jsx
  zipkin-lens/src/components/common/LoadingIndicator.tsx
  zipkin-lens/src/components/common/TraceJsonUploader.jsx
  zipkin-lens/src/models/AdjustedTrace.ts
  zipkin-lens/src/models/Annotation.ts
  zipkin-lens/src/models/Endpoint.ts
  zipkin-lens/src/models/Span.ts
  zipkin-lens/src/reducers/index.ts
  zipkin-lens/src/reducers/trace-viewer.js
  zipkin-lens/src/reducers/trace.js
  zipkin-lens/src/reducers/trace.test.js
  zipkin-lens/src/reducers/traces.js
  zipkin-lens/src/reducers/traces.test.js
  zipkin-lens/src/slices/tracesSlice.test.ts
  zipkin-lens/src/slices/tracesSlice.ts
  zipkin-lens/src/types/redux-thunk.d.ts
  zipkin-lens/src/zipkin/trace.js
  zipkin-lens/src/zipkin/trace.test.js
Labels: techdebt, ui
