Repository openzipkin/zipkin, pull requests merged in 2020-08, with the labels that each got.

#3156 Stops using prepared or query builder statements for simple queries
  zipkin-server/README.md
  zipkin-server/src/main/resources/zipkin-server-shared.yml
  zipkin-storage/cassandra-v1/README.md
  zipkin-storage/cassandra-v1/src/main/java/zipkin2/storage/cassandra/v1/CassandraStorage.java
  zipkin-storage/cassandra-v1/src/main/java/zipkin2/storage/cassandra/v1/SelectServiceNames.java
  zipkin-storage/cassandra-v1/src/test/resources/simplelogger.properties
  zipkin-storage/cassandra/README.md
  zipkin-storage/cassandra/src/main/java/zipkin2/storage/cassandra/CassandraStorage.java
  zipkin-storage/cassandra/src/main/java/zipkin2/storage/cassandra/SelectServiceNames.java
  zipkin-storage/cassandra/src/test/resources/simplelogger.properties
Labels: cassandra

#3172 Use redux-toolkit to reduce boilerplate code
  zipkin-lens/src/actions/autocomplete-keys-action.js
  zipkin-lens/src/actions/autocomplete-keys-action.test.js
  zipkin-lens/src/actions/autocomplete-values-action.js
  zipkin-lens/src/actions/autocomplete-values-action.test.js
  zipkin-lens/src/actions/remote-services-action.js
  zipkin-lens/src/actions/remote-services-action.test.js
  zipkin-lens/src/actions/services-action.js
  zipkin-lens/src/actions/services-action.test.js
  zipkin-lens/src/actions/spans-action.js
  zipkin-lens/src/actions/spans-action.test.js
  zipkin-lens/src/components/DiscoverPage/DiscoverPage.tsx
  zipkin-lens/src/components/DiscoverPage/SearchBar/SearchBar.tsx
  zipkin-lens/src/constants/action-types.js
  zipkin-lens/src/reducers/autocomplete-keys.js
  zipkin-lens/src/reducers/autocomplete-keys.test.js
  zipkin-lens/src/reducers/autocomplete-values.js
  zipkin-lens/src/reducers/autocomplete-values.test.js
  zipkin-lens/src/reducers/index.ts
  zipkin-lens/src/reducers/remote-services.js
  zipkin-lens/src/reducers/remote-services.test.js
  zipkin-lens/src/reducers/services.js
  zipkin-lens/src/reducers/services.test.js
  zipkin-lens/src/reducers/spans.js
  zipkin-lens/src/reducers/spans.test.js
  zipkin-lens/src/slices/autocompleteKeysSlice.ts
  zipkin-lens/src/slices/autocompleteValuesSlice.ts
  zipkin-lens/src/slices/remoteServicesSlice.ts
  zipkin-lens/src/slices/servicesSlice.ts
  zipkin-lens/src/slices/spansSlice.ts
Labels: enhancement, ui

#3169 Update sidebar and header design
  zipkin-lens/package-lock.json
  zipkin-lens/package.json
  zipkin-lens/src/colors/index.ts
  zipkin-lens/src/components/App/HeaderMenuItem.tsx
  zipkin-lens/src/components/App/LanguageSelector.test.tsx
  zipkin-lens/src/components/App/LanguageSelector.tsx
  zipkin-lens/src/components/App/Layout.jsx
  zipkin-lens/src/components/App/Layout.test.jsx
  zipkin-lens/src/components/App/SidebarMenu.test.tsx
  zipkin-lens/src/components/App/SidebarMenu.tsx
  zipkin-lens/src/components/Common/ExplainBox.tsx
  zipkin-lens/src/components/DiscoverPage/DiscoverPage.tsx
  zipkin-lens/src/components/DiscoverPage/DiscoverPageContent.test.jsx
  zipkin-lens/src/components/DiscoverPage/DiscoverPageContent.tsx
  zipkin-lens/src/components/DiscoverPage/ExplainBox.tsx
  zipkin-lens/src/components/DiscoverPage/LookbackMenu.tsx
  zipkin-lens/src/components/DiscoverPage/SearchBar/SearchBar.tsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTab.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTable.jsx
  zipkin-lens/src/components/TracePage/TraceSummary.jsx
  zipkin-lens/src/components/TracePage/TraceSummaryHeader.jsx
  zipkin-lens/src/css/base.css
  zipkin-lens/src/dependencies/DependenciesGraph.tsx
  zipkin-lens/src/dependencies/DependenciesPage.test.jsx
  zipkin-lens/src/dependencies/DependenciesPage.tsx
  zipkin-lens/src/dependencies/ExplainBox.tsx
  zipkin-lens/src/dependencies/NodeDetailData.tsx
  zipkin-lens/src/translations/en/messages.js
  zipkin-lens/src/translations/en/messages.json
  zipkin-lens/src/translations/es/messages.js
  zipkin-lens/src/translations/es/messages.json
  zipkin-lens/src/translations/zh-cn/messages.js
  zipkin-lens/src/translations/zh-cn/messages.json
Labels: enhancement, ui

#3191 Use react-use instead of own hooks
  zipkin-lens/src/components/App/App.tsx
  zipkin-lens/src/hooks/index.js
  zipkin-lens/src/hooks/useDocumentTitle.js
  zipkin-lens/src/hooks/useEffectOnce.js
  zipkin-lens/src/hooks/useMount.js
  zipkin-lens/src/hooks/useUnmount.js
Labels: techdebt, ui

#3193 Change directory structure
  zipkin-lens/src/components/App/App.tsx
  zipkin-lens/src/components/App/Layout.jsx
  zipkin-lens/src/components/DependenciesPage/DependenciesGraph.test.jsx
  zipkin-lens/src/components/DependenciesPage/DependenciesGraph.tsx
  zipkin-lens/src/components/DependenciesPage/DependenciesPage.test.jsx
  zipkin-lens/src/components/DependenciesPage/DependenciesPage.tsx
  zipkin-lens/src/components/DependenciesPage/Edge.ts
  zipkin-lens/src/components/DependenciesPage/NodeDetailData.test.jsx
  zipkin-lens/src/components/DependenciesPage/NodeDetailData.tsx
  zipkin-lens/src/components/DependenciesPage/VizceralWrapper.tsx
  zipkin-lens/src/components/DependenciesPage/index.ts
  zipkin-lens/src/components/DiscoverPage/DiscoverPageContent.tsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/ServiceFilterPopover.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableRow.jsx
  zipkin-lens/src/components/DiscoverPage/TracesTab/TracesTableRow.test.js
  zipkin-lens/src/components/TracePage/SpanDetail/SpanAnnotationGraph.jsx
  zipkin-lens/src/components/TracePage/TraceTimeline/TraceTimelineRow.jsx
  zipkin-lens/src/components/TracePage/TraceTimeline/TraceTree.jsx
  zipkin-lens/src/components/TracePage/TraceTimelineHeader/TraceTimelineHeader.test.js
  zipkin-lens/src/components/common/ExplainBox.tsx
  zipkin-lens/src/components/common/ServiceBadge.jsx
  zipkin-lens/src/components/common/ServiceBadge.test.js
  zipkin-lens/src/components/common/TraceIdSearchInput.jsx
  zipkin-lens/src/components/common/TraceIdSearchInput.test.js
  zipkin-lens/src/components/common/TraceJsonUploader.jsx
  zipkin-lens/src/constants/color.ts
  zipkin-lens/src/test/util/render-with-default-settings.tsx
Labels: techdebt, ui
